# Generated by Django 5.1.15 on 2026-04-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='documentapproval',
            unique_together={('document', 'step_order')},
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['organization', 'status'], name='api_documen_organiz_d35d61_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['organization', 'created_by'], name='api_documen_organiz_d0fe10_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['organization', '-created_at'], name='api_documen_organiz_95e6f1_idx'),
        ),
        migrations.AddIndex(
            model_name='documentapproval',
            index=models.Index(fields=['document', 'step_order'], name='api_documen_documen_013231_idx'),
        ),
        migrations.AddIndex(
            model_name='documentapproval',
            index=models.Index(fields=['user', 'status'], name='api_documen_user_id_577ac2_idx'),
        ),
    ]
