# Generated by Django 5.1.15 on 2026-04-11 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_documentapproval_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentversion',
            name='file_type',
            field=models.CharField(default='application/pdf', max_length=100),
        ),
        migrations.AddField(
            model_name='workflow',
            name='sendback_type',
            field=models.CharField(choices=[('PREVIOUS_ONLY', 'Previous Step Only'), ('ANY_PREVIOUS', 'Any Previous Step')], default='PREVIOUS_ONLY', max_length=15),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='documentapproval',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10),
        ),
    ]
